CREATE table "CUSTOMERS" (
    "CUSTOMER_NUM"    NUMBER NOT NULL,
    "CUSTOMER_FNAME"  VARCHAR2(32) NOT NULL,
    "CUSTOMER_LNAME"  VARCHAR2(32),
    "CUSTOMER_ID"     NUMBER NOT NULL,
    "CUSTOMER_STREET" VARCHAR2(64),
    "CUSTOMER_CITY"   VARCHAR2(32),
    "CUSTOMER_PHONE"  VARCHAR2(32),
    constraint  "CUSTOMERS_PK" primary key ("CUSTOMER_NUM")
)
/

alter table "CUSTOMERS" add
constraint "CUSTOMERS_UK_ID" 
unique ("CUSTOMER_ID")
/
