CREATE table "ORDERS" (
    "ORDER_NUM"    NUMBER NOT NULL,
    "ORDER_DATE"   DATE NOT NULL,
    "CUSTOMER_NUM" NUMBER NOT NULL,
    "ORDER_PRICE"  FLOAT NOT NULL,
    "ORDER_STATUS" VARCHAR2(10) NOT NULL,
    constraint  "ORDERS_PK" primary key ("ORDER_NUM")
)
/

ALTER TABLE "ORDERS" ADD CONSTRAINT "ORDERS_CUSTOMER_FK" 
FOREIGN KEY ("CUSTOMER_NUM")
REFERENCES "CUSTOMERS" ("CUSTOMER_NUM")

/
