CREATE table "STOCK" (
    "ITEM_NUM"       NUMBER NOT NULL,
    "WH_NUM"         NUMBER NOT NULL,
    "STOCK_QUANTITY" NUMBER NOT NULL
)
/

alter table "STOCK" add constraint  "STOCK_PK" primary key ("ITEM_NUM","WH_NUM")
/

ALTER TABLE "STOCK" ADD CONSTRAINT "STOCK_ITEM_FK" 
FOREIGN KEY ("ITEM_NUM")
REFERENCES "ITEMS" ("ITEM_NUM")
ON DELETE CASCADE

/
ALTER TABLE "STOCK" ADD CONSTRAINT "STOCK_WH_FK" 
FOREIGN KEY ("WH_NUM")
REFERENCES "WAREHOUSES" ("WH_NUM")
ON DELETE CASCADE

/
